{% set name = "napari-skimage" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_skimage-{{ version }}.tar.gz
  sha256: a483831e6bd2ae7ee762d0fe78ea98e7d76fe56de26630d1bd32cb12b591b5f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42.0.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - napari
    - numpy
    - magicgui
    - qtpy
    - scikit-image

test:
  imports:
    - napari_skimage
  commands:
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-skimage/
  summary: A napari plugin to apply scikit-image operations
  dev_url: https://github.com/guiwitz/napari-skimage
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guiwitz
